// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFgV7xJz_ppHU97oZVlKZ4COGK1GoI_m0',
    appId: '1:301975725212:web:57c269bf5ab98ba40a3959',
    messagingSenderId: '301975725212',
    projectId: 'todos-15a30',
    authDomain: 'todos-15a30.firebaseapp.com',
    storageBucket: 'todos-15a30.firebasestorage.app',
    measurementId: 'G-8PT627GHLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBY-9Pj4k_AcebD0clpvVCeCD9-QOdMn14',
    appId: '1:301975725212:android:2e9ec3eb21d2f5c40a3959',
    messagingSenderId: '301975725212',
    projectId: 'todos-15a30',
    storageBucket: 'todos-15a30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXvqxhbPNXlL1PdZEWzwqVXMs8K572otk',
    appId: '1:301975725212:ios:58e8f6ba9051e6f20a3959',
    messagingSenderId: '301975725212',
    projectId: 'todos-15a30',
    storageBucket: 'todos-15a30.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXvqxhbPNXlL1PdZEWzwqVXMs8K572otk',
    appId: '1:301975725212:ios:58e8f6ba9051e6f20a3959',
    messagingSenderId: '301975725212',
    projectId: 'todos-15a30',
    storageBucket: 'todos-15a30.firebasestorage.app',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFgV7xJz_ppHU97oZVlKZ4COGK1GoI_m0',
    appId: '1:301975725212:web:f066f9765d371c2c0a3959',
    messagingSenderId: '301975725212',
    projectId: 'todos-15a30',
    authDomain: 'todos-15a30.firebaseapp.com',
    storageBucket: 'todos-15a30.firebasestorage.app',
    measurementId: 'G-SXJZV24HGW',
  );
}
